### ISSUE TITLE
Scrolls to far

### ISSUE THREAD

**Issue by lawloretienne** [rubensousa/RecyclerViewSnap#2] opened 2016-08-31 20:30 UTC
So i started testing out this GravitySnapHelper and i noticed a very subtle issue that arises after continually testing.  So its difficult to reproduce every single time but i have tested it enough to reproduce it several times.  

If you are scrolling through the `RecyclerView` with a swipe gesture, your finger remains on the screen and you let go while the second half of an item ( lets say item number 5) in the adapter shows then it slides to the left so then item number 6 is the furthest left item to show.  

Now if you are scrolling through the `RecyclerView` with a swipe gesture, your finger remains on the screen and you let go while the first half of an item ( lets say item number 5) in the adapter shows then it slides to the left so then item number 5 is the furthest left item to show.  

Once in awhile, if you are scrolling through the `RecyclerView` with a swipe gesture, your finger remains on the screen and you let go while the first half of an item ( lets say item number 5) in the adapter shows then it slides to the left so then item number 4 is the furthest left item to show.  So in this case it slides too far.

**Comment by rubensousa** [comment] 2016-08-31 22:42
I think you're describing a fling gesture, but I'm not sure. If you swipe fast enough, the recyclerview will scroll for more items. Isn't this what's happening? You can control the fling speed, but it's out of context for this sample. If I'm mistaken, please provide a gif that reproduces this so I can take a look.

**Comment by lawloretienne** [comment] 2016-08-31 23:09
Check out this video.  It shows the issue i'm talking about.
https://goo.gl/photos/TSmEL6AvdeiDThJ78

**Comment by rubensousa** [comment] 2016-08-31 23:14
Oh, I see now. This also happened to me a couple of times. I'll take a look at this later.

**Comment by rubensousa** [comment] 2016-09-25 02:05
Should be fixed in release 0.2

**Closed as completed by rubensousa** 2016-09-25 02:05 UTC
Labels: needs more info

**Comment by rubensousa** [comment] 2016-09-25 13:48
Fixed properly in 0.3. I've opened an issue in the official bug tracker since this problem was due to LinearSnapHelper: https://code.google.com/p/android/issues/detail?id=223649
