### ISSUE TITLE
java.lang.IllegalStateException: An instance of OnFlingListener already set.

### ISSUE THREAD

**Issue by wuxiaojun123** [rubensousa/RecyclerViewSnap#42] opened 2017-12-13 08:35 UTC
java.lang.IllegalStateException: An instance of OnFlingListener already set.
                                                                                          at android.support.v7.widget.SnapHelper.setupCallbacks(SnapHelper.java:115)
                                                                                          at android.support.v7.widget.SnapHelper.attachToRecyclerView(SnapHelper.java:103)
                                                                                          at com.github.rubensousa.recyclerviewsnap.SnapAdapter.onBindViewHolder(SnapAdapter.java:92)
                                                                                          at com.github.rubensousa.recyclerviewsnap.SnapAdapter.onBindViewHolder(SnapAdapter.java:20)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                                          at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                                          at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                                          at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                                          at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                                          at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                          at android.os.Looper.loop(Looper.java:194)
                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5868)
                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by rubensousa** [comment] 2017-12-13 10:43
Duplicate of: https://github.com/rubensousa/RecyclerViewSnap/issues/23
This was fixed already on 1.3

**Closed as completed by rubensousa** 2017-12-13 10:43 UTC

**Comment by Danish1111** [comment] 2018-03-03 10:09
please describe how to fix this issue?
